# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Nombre',
        ),
        migrations.AddField(
            model_name='post',
            name='Stock',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
