# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20160501_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Imagen',
            field=models.FileField(upload_to='images/'),
        ),
    ]
