# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_post_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Cafe',
        ),
    ]
